Repository milieuinfo/webcomponent-vl-ui-proza-message, pull requests merged in 2020-01, with the labels that each got.

#19 Stop bewerk button klik event
  test/unit/vl-proza-message.test.html
  vl-proza-message.src.js
Labels: bug

#20 Block attribuut introductie en block rendering geoptimaliseerd
  style.css
  style.css.map
  style.scss
  test/unit/vl-proza-message.test.html
  vl-proza-message.src.js
Labels: enhancement

#21 E2E Testen
  .gitignore
  demo/demo.css
  demo/demo.css.map
  demo/vl-proza-message.html
  package-lock.json
  package.json
  style.css
  style.css.map
  test/e2e/components/vl-proza-message.js
  test/e2e/pages/vl-proza-message.page.js
  test/e2e/proza-message.test.js
  vl-proza-message.src.js
Labels: chore

#23 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#24 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#25 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance

#27 #26: Fix het gebruik van TinyMCE in shadow DOM
  dist/tinymce.min.js
  package-lock.json
  package.json
  style.css
  style.css.map
  style.scss
  vl-proza-message.js
  vl-proza-message.src.js
Labels: bug

#30 #29: Toon gele border enkel indien message bewerkbaar is
  test/unit/vl-proza-message.test.html
  vl-proza-message.js
  vl-proza-message.src.js
Labels: bug
