Repository milieuinfo/webcomponent-vl-ui-proza-message, pull requests merged in 2020-04, with the labels that each got.

#35 Update dependency tinymce to v5.2.1
  package-lock.json
  package.json
Labels: dependencies

#45 Update dependency vl-ui-util to v5.1.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#51 Oplossing voor flaky testen
  package-lock.json
  package.json
  test/unit/vl-proza-message.test.html
Labels: chore

#52 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore

#54 Update dependency tinymce to v5.2.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
