Repository milieuinfo/webcomponent-vl-ui-proza-message, pull requests merged in 2020-03, with the labels that each got.

#39 E2E testen
  .mocharc.js
  package-lock.json
  package.json
  test/e2e/components/vl-proza-message.js
  test/e2e/pages/vl-proza-message.page.js
  test/e2e/proza-message.test.js
  test/unit/vl-proza-message.test.html
Labels: chore

#40 Update vl-ui-util
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: chore, maintenance

#42 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore

#43 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore

#44 Andere TinyMCE lib gebruiken
  lib/tinymce.min.js
  package-lock.json
  package.json
Labels: bug
