Repository milieuinfo/webcomponent-vl-ui-proza-message, pull requests merged in 2020-06, with the labels that each got.

#59 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/vl-proza-message.html
  index.js
  package-lock.json
  package.json
  src/index.js
  src/style.css
  src/style.css.map
  src/vl-proza-message.js
  test/e2e/components/vl-proza-message.js
  test/e2e/pages/vl-proza-message.page.js
  test/e2e/proza-message.test.js
  test/unit/preloaded-vl-proza-message.test.html
  test/unit/vl-proza-message-preloader.test.html
  test/unit/vl-proza-message.test.html
Labels: chore

#60 Fix pad naar fetch-mock esm.js
  demo/vl-proza-message.html
  package-lock.json
  test/e2e/components/vl-proza-message.js
  test/unit/vl-proza-message-preloader.test.html
  test/unit/vl-proza-message.test.html
Labels: bugfix

#66 Update dependency tinymce to v5.3.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#67 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
  src/vl-proza-message.js
Labels: bug

#69 Deduplicatie NPM run scripts
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore
